"""SentinalIQ - Activity Report Generation & Email Delivery

Generates a polished PDF report of a user's security activity
(website monitoring, URL scans, file uploads, monitor events, incidents)
and emails it to the user's registered email address via SMTP.

SMTP configuration (via environment variables):
    GMAIL_USER           - sender Gmail address (e.g. your.name@gmail.com)
    GMAIL_APP_PASSWORD   - Gmail App Password (16-char, NOT your normal password)
    SMTP_HOST            - default smtp.gmail.com
    SMTP_PORT            - default 587
    SMTP_FROM            - optional "From" display name/address override

If GMAIL_USER is not set, sending is skipped and the PDF is returned/saved
locally so the feature can be tested without credentials.
"""

import os
import smtplib
from datetime import datetime, timezone
from email.mime.application import MIMEApplication
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

from fpdf import FPDF

# ─── Colors (SentinalIQ dark cyberpunk palette) ─────────────────────────────

PAGE_BG = (9, 13, 23)          # near-black page background
DARK_BG = (13, 18, 30)         # header strip / cover panel
CARD_BG = (24, 33, 55)         # table header / cells
ROW_BG = (16, 22, 38)          # table body rows
BORDER = (42, 54, 82)          # subtle cell borders
CYAN = (6, 182, 212)
TEXT_MUTED = (156, 172, 196)   # light gray-blue secondary text
WHITE = (255, 255, 255)        # body text / values


def _env_or(key: str, default: str) -> str:
    return os.environ.get(key, default)


# Placeholder tokens from the shipped .env template — if these are still present
# the user hasn't filled in real credentials yet.
_PLACEHOLDER_TOKENS = ("yourname", "your-16-char", "<your", "changeme")


def is_smtp_configured() -> bool:
    """True if a real sender account has been configured to send email.
    Returns False when values are missing OR still the .env placeholders,
    so the UI shows the friendly 'not configured' message instead of
    attempting an SMTP login with dummy credentials."""
    user = _env_or("GMAIL_USER", "").strip()
    password = _env_or("GMAIL_APP_PASSWORD", "").strip()
    if not user or not password:
        return False
    if any(tok in user.lower() or tok in password.lower() for tok in _PLACEHOLDER_TOKENS):
        return False
    return True


# ─── PDF Helpers ────────────────────────────────────────────────────────────

def _safe_text(value) -> str:
    """Convert values to a cp1252-safe str (fpdf2 core fonts encode with cp1252).
    Unsupported characters are replaced rather than crashing generation."""
    text = str(value if value is not None else "")
    return text.encode("cp1252", errors="replace").decode("cp1252").strip()


class ReportPDF(FPDF):
    """Custom PDF with header/footer for the security report."""

    def __init__(self, username: str = ""):
        super().__init__()
        self.set_auto_page_break(auto=True, margin=24)
        self.username = _safe_text(username)

    def header(self):
        # Dark page background (drawn on every page)
        self.set_fill_color(*PAGE_BG)
        self.rect(0, 0, self.w, self.h, "F")
        # Top accent strip
        self.set_fill_color(*DARK_BG)
        self.rect(0, 0, self.w, 18, "F")
        self.set_font("Helvetica", "B", 9)
        self.set_text_color(*CYAN)
        self.set_xy(10, 6)
        self.cell(0, 6, "SENTINALIQ", new_x="LMARGIN", new_y="NEXT")
        self.set_font("Helvetica", "", 8)
        self.set_text_color(*TEXT_MUTED)
        self.set_xy(10, 12)
        self.cell(0, 4, f"Security Activity Report  |  {self.username}", new_x="LMARGIN", new_y="NEXT")

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 7)
        self.set_text_color(*TEXT_MUTED)
        self.cell(0, 10, f"Generated by SentinalIQ  |  Page {self.page_no()}", align="C")

    def section_title(self, title: str):
        self.ln(3)
        self.set_font("Helvetica", "B", 11)
        self.set_text_color(*CYAN)
        self.cell(0, 8, _safe_text(title), new_x="LMARGIN", new_y="NEXT")
        self.set_draw_color(*CYAN)
        self.set_line_width(0.5)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(2)

    def table(self, headers, rows, col_widths=None):
        col_widths = col_widths or [50] * len(headers)
        self.set_draw_color(*BORDER)
        # Header row
        self.set_font("Helvetica", "B", 8)
        self.set_fill_color(*CARD_BG)
        self.set_text_color(*CYAN)
        for i, h in enumerate(headers):
            self.cell(col_widths[i], 7, _safe_text(h), border=1, fill=True, align="L")
        self.ln()
        # Body rows (dark cells, white text)
        self.set_font("Helvetica", "", 8)
        self.set_text_color(*WHITE)
        self.set_fill_color(*ROW_BG)
        for row in rows:
            if self.get_y() > 262:
                self.add_page()
            for i, cell in enumerate(row):
                self.cell(col_widths[i], 6.5, _safe_text(cell)[:60], border=1, fill=True)
            self.ln()


def build_user_report_pdf(user, stats: dict, websites: list, ingests: list,
                          monitor_events: list, incidents: list) -> bytes:
    """Build the full PDF report and return it as bytes."""
    now = datetime.now(timezone.utc)
    pdf = ReportPDF(username=user.username)

    # ── Cover / Summary ─────────────────────────────────────────────────────
    pdf.add_page()
    pdf.set_fill_color(*DARK_BG)
    pdf.rect(0, 30, 210, 90, "F")
    pdf.set_font("Helvetica", "B", 26)
    pdf.set_text_color(*CYAN)
    pdf.set_xy(12, 44)
    pdf.cell(0, 12, "SENTINALIQ", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "B", 17)
    pdf.set_text_color(*WHITE)
    pdf.set_xy(12, 60)
    pdf.cell(0, 10, "Security Activity Report", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(*TEXT_MUTED)
    pdf.set_xy(12, 76)
    pdf.cell(0, 6, f"Prepared for: {_safe_text(user.username)}  ({_safe_text(user.email)})",
             new_x="LMARGIN", new_y="NEXT")
    pdf.set_xy(12, 84)
    pdf.cell(0, 6, f"Generated: {now.strftime('%B %d, %Y  %H:%M UTC')}", new_x="LMARGIN", new_y="NEXT")
    pdf.set_xy(12, 96)
    pdf.set_font("Helvetica", "B", 10)
    pdf.set_text_color(*CYAN)
    pdf.cell(0, 6, f"Security Score: {stats.get('security_score', 0)} / 100", new_x="LMARGIN", new_y="NEXT")

    # ── Summary stats ───────────────────────────────────────────────────────
    pdf.set_y(128)
    pdf.section_title("Summary")
    summary_rows = [
        ("Websites Monitored", stats.get("monitored_websites", 0)),
        ("URL Scans", stats.get("my_scans", 0)),
        ("File Uploads", stats.get("my_uploads", 0)),
        ("Records Imported", stats.get("my_total_imported", 0)),
        ("Total Incidents", stats.get("total_incidents", 0)),
        ("Critical Incidents", stats.get("critical_incidents", 0)),
        ("Monitor Events Today", stats.get("monitor_events_today", 0)),
        ("Active IOCs", stats.get("total_iocs", 0)),
        ("WAF Blocks", stats.get("waf_blocked", 0)),
    ]
    col_width = 63
    for i in range(0, len(summary_rows), 3):
        for j, (label, value) in enumerate(summary_rows[i:i + 3]):
            pdf.set_x(10 + j * col_width)
            pdf.set_font("Helvetica", "", 8.5)
            pdf.set_text_color(*TEXT_MUTED)
            pdf.cell(col_width - 10, 6, _safe_text(label), new_x="RIGHT")
            pdf.set_font("Helvetica", "B", 9.5)
            pdf.set_text_color(*WHITE)
            pdf.cell(10, 6, _safe_text(value)[:8], new_x="RIGHT")
        pdf.ln(7)

    # ── Websites monitored ──────────────────────────────────────────────────
    pdf.section_title("Websites Under Monitoring")
    if websites:
        rows = []
        for w in websites:
            rows.append([
                w.get("hostname") or w.get("url", ""),
                w.get("threat_score", 0),
                (w.get("threat_level") or "safe").title(),
                w.get("status", "").replace("_", " ").title(),
                w.get("scan_count", 0),
            ])
        pdf.table(["Website", "Score", "Level", "Status", "Scans"], rows,
                  col_widths=[84, 20, 28, 38, 20])
    else:
        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(*TEXT_MUTED)
        pdf.cell(0, 7, "No websites are currently under monitoring.", new_x="LMARGIN", new_y="NEXT")

    # ── Recent activity (ingestion) ─────────────────────────────────────────
    pdf.section_title("Recent URL Scans & Uploads")
    if ingests:
        rows = []
        for rec in ingests:
            rows.append([
                "URL Scan" if rec.get("type") == "url_scan" else "File Upload",
                (rec.get("source") or "")[:42],
                rec.get("records_count", 0),
                rec.get("status", "").title(),
            ])
        pdf.table(["Type", "Source", "Records", "Status"], rows, col_widths=[34, 96, 26, 30])
    else:
        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(*TEXT_MUTED)
        pdf.cell(0, 7, "No scans or uploads recorded yet.", new_x="LMARGIN", new_y="NEXT")

    # ── Monitor events ──────────────────────────────────────────────────────
    pdf.section_title("Live Monitoring Events")
    if monitor_events:
        rows = []
        for ev in monitor_events:
            rows.append([
                (ev.get("timestamp") or "")[:19].replace("T", " "),
                ev.get("event_type", "").replace("_", " ").title(),
                ev.get("severity", "").title(),
                ev.get("source_ip", ""),
                ev.get("status", "").title(),
            ])
        pdf.table(["Time (UTC)", "Type", "Severity", "Source IP", "Status"], rows,
                  col_widths=[40, 44, 26, 36, 28])
    else:
        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(*TEXT_MUTED)
        pdf.cell(0, 7, "No monitoring events detected in the selected period.", new_x="LMARGIN", new_y="NEXT")

    # ── Incidents ───────────────────────────────────────────────────────────
    pdf.section_title("Incidents")
    if incidents:
        rows = []
        for inc in incidents:
            rows.append([
                (inc.get("created_at") or "")[:10],
                inc.get("severity", "").title(),
                (inc.get("title") or "")[:52],
                inc.get("status", "").title(),
            ])
        pdf.table(["Date", "Severity", "Title", "Status"], rows,
                  col_widths=[22, 24, 112, 28])
    else:
        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(*TEXT_MUTED)
        pdf.cell(0, 7, "No incidents recorded.", new_x="LMARGIN", new_y="NEXT")

    pdf.ln(6)
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(*TEXT_MUTED)
    pdf.cell(0, 5, "This report was generated automatically by SentinalIQ. For questions contact your SOC team.",
             new_x="LMARGIN", new_y="NEXT")

    # fpdf2's output() returns a bytearray; convert to bytes so Starlette's
    # Response.render() (which only accepts bytes) doesn't crash.
    return bytes(pdf.output())


# ─── Email Sending ──────────────────────────────────────────────────────────

def send_report_email(to_email: str, pdf_bytes: bytes, username: str = "") -> dict:
    """Email the PDF report to the user. Returns {sent, reason}."""
    if not is_smtp_configured():
        return {
            "sent": False,
            "reason": "SMTP not configured — fill in GMAIL_USER and GMAIL_APP_PASSWORD in backend/.env and restart the server.",
        }

    smtp_host = _env_or("SMTP_HOST", "smtp.gmail.com")
    smtp_port = int(_env_or("SMTP_PORT", "587"))
    sender = _env_or("GMAIL_USER", "")
    app_password = _env_or("GMAIL_APP_PASSWORD", "")

    subject = f"SentinalIQ Security Report — {username or 'Your Activity'}"
    html_body = f"""\
<html><body style="font-family:Arial,sans-serif;background:#0d121e;padding:24px;">
  <div style="max-width:560px;margin:auto;background:#1b2438;border-radius:12px;padding:28px;border:1px solid #24324d;">
    <div style="font-size:20px;font-weight:bold;color:#06b6d4;margin-bottom:4px;">SentinalIQ</div>
    <div style="color:#e2e8f0;font-size:15px;margin-bottom:16px;">Your security activity report is ready.</div>
    <p style="color:#94a3b8;font-size:13px;line-height:1.6;">
      Hi {username or 'there'},<br/><br/>
      Please find attached your latest <b>SentinalIQ Security Activity Report (PDF)</b>,
      covering your website monitoring, URL scans, file uploads, live monitoring events,
      and incidents.<br/><br/>
      Review it to stay on top of your security posture.
    </p>
    <div style="margin-top:16px;font-size:11px;color:#64748b;">
      This is an automated message from SentinalIQ. Do not reply to this email.
    </div>
  </div>
</body></html>"""

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = _env_or("SMTP_FROM", f"SentinalIQ <{sender}>")
    msg["To"] = to_email
    msg.attach(MIMEText(html_body, "html"))

    attachment = MIMEApplication(pdf_bytes, _subtype="pdf")
    filename = f"sentinaliq-report-{datetime.now(timezone.utc).strftime('%Y%m%d-%H%M')}.pdf"
    attachment.add_header("Content-Disposition", "attachment", filename=filename)
    msg.attach(attachment)

    try:
        with smtplib.SMTP(smtp_host, smtp_port, timeout=30) as server:
            server.starttls()
            server.login(sender, app_password)
            server.sendmail(sender, [to_email], msg.as_string())
        return {"sent": True, "reason": f"Report emailed to {to_email}"}
    except Exception as e:
        return {"sent": False, "reason": f"Email failed: {type(e).__name__}: {str(e)[:200]}"}
